"""Revertir plu_coins a plucoins

Revision ID: 63442b7e59c0
Revises: 9f0ced2eab9a
Create Date: 2025-04-22 19:26:33.642349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63442b7e59c0'
down_revision = '9f0ced2eab9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plucoins', sa.Integer(), nullable=True))
        batch_op.drop_column('plu_coins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plu_coins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('plucoins')

    # ### end Alembic commands ###
