"""Add WhatsappConnection model

Revision ID: 71a2253ef098
Revises: 5bcb53ffdd6d
Create Date: 2025-06-23 05:13:45.807527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a2253ef098'
down_revision = '5bcb53ffdd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plubot_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plubot_id'], ['plubots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plubot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_connections')
    # ### end Alembic commands ###
