"""Add plubot_id column to knowledge_items table

Revision ID: 9736b8e4922c
Revises: a69b6a1294e0
Create Date: 2025-07-04 04:06:52.000218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9736b8e4922c'
down_revision = 'a69b6a1294e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('conversation_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('conversation_states_current_node_id_fkey', 'conversation_states', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_states', 'flows', ['current_node_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('conversations_chatbot_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'plubots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.alter_column('discord_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('discord_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('discord_integrations_user_id_fkey', 'discord_integrations', type_='foreignkey')
    op.create_foreign_key(None, 'discord_integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('flow_edges', 'condition',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('flow_edges', 'edge_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('flow_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flow_edges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flow_edges', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('flows', 'condition',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.execute("UPDATE flows SET node_type = 'message' WHERE node_type IS NULL")
    op.alter_column('flows', 'node_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flows', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # --- Start of custom data migration for plubot_id ---
    op.add_column('knowledge_items', sa.Column('plubot_id', sa.Integer(), nullable=True))

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Define a simple table representation for querying
    plubot_table = sa.Table('plubots', sa.MetaData(), sa.Column('id', sa.Integer, primary_key=True))

    # Check if any plubot exists
    first_plubot = session.query(plubot_table).first()

    if first_plubot:
        # If plubots exist, assign the first plubot's ID to all knowledge items
        plubot_id = first_plubot.id
        op.execute(f'UPDATE knowledge_items SET plubot_id = {plubot_id}')
    else:
        # If no plubots exist, any existing knowledge items are orphans and should be removed
        # to satisfy the foreign key constraint that will be added.
        op.execute('DELETE FROM knowledge_items')

    # Now, make the column non-nullable
    op.alter_column('knowledge_items', 'plubot_id',
               existing_type=sa.Integer(),
               nullable=False)
    # --- End of custom data migration for plubot_id ---
    op.add_column('knowledge_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE knowledge_items SET created_at = NOW() WHERE created_at IS NULL')
    op.alter_column('knowledge_items', 'created_at', existing_type=sa.DateTime(), nullable=False)

    op.add_column('knowledge_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE knowledge_items SET updated_at = NOW() WHERE updated_at IS NULL')
    op.alter_column('knowledge_items', 'updated_at', existing_type=sa.DateTime(), nullable=False)
    op.alter_column('knowledge_items', 'keywords',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'knowledge_items', 'plubots', ['plubot_id'], ['id'], ondelete='CASCADE')
    op.add_column('message_quotas', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE message_quotas SET created_at = NOW() WHERE created_at IS NULL')
    op.alter_column('message_quotas', 'created_at', existing_type=sa.DateTime(), nullable=False)

    op.add_column('message_quotas', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE message_quotas SET updated_at = NOW() WHERE updated_at IS NULL')
    op.alter_column('message_quotas', 'updated_at', existing_type=sa.DateTime(), nullable=False)
    op.alter_column('message_quotas', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message_quotas', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('_user_month_uc', 'message_quotas', ['user_id', 'month'])
    op.drop_constraint('message_quotas_user_id_fkey', 'message_quotas', type_='foreignkey')
    op.create_foreign_key(None, 'message_quotas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute('UPDATE plubots SET created_at = NOW() WHERE created_at IS NULL')
    op.alter_column('plubots', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.execute('UPDATE plubots SET updated_at = NOW() WHERE updated_at IS NULL')
    op.alter_column('plubots', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_unique_constraint(None, 'templates', ['name'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'plucoins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('whatsapp_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('whatsapp_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('whatsapp_connections_plubot_id_fkey', 'whatsapp_connections', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp_connections', 'plubots', ['plubot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_connections', type_='foreignkey')
    op.create_foreign_key('whatsapp_connections_plubot_id_fkey', 'whatsapp_connections', 'plubots', ['plubot_id'], ['id'])
    op.alter_column('whatsapp_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('whatsapp_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'plucoins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'templates', type_='unique')
    op.alter_column('plubots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('plubots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'message_quotas', type_='foreignkey')
    op.create_foreign_key('message_quotas_user_id_fkey', 'message_quotas', 'users', ['user_id'], ['id'])
    op.drop_constraint('_user_month_uc', 'message_quotas', type_='unique')
    op.alter_column('message_quotas', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message_quotas', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('message_quotas', 'updated_at')
    op.drop_column('message_quotas', 'created_at')
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.alter_column('knowledge_items', 'keywords',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('knowledge_items', 'updated_at')
    op.drop_column('knowledge_items', 'created_at')
    op.drop_column('knowledge_items', 'plubot_id')
    op.alter_column('flows', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flows', 'node_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('flows', 'condition',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('flow_edges', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('flow_edges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flow_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flow_edges', 'edge_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('flow_edges', 'condition',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint(None, 'discord_integrations', type_='foreignkey')
    op.create_foreign_key('discord_integrations_user_id_fkey', 'discord_integrations', 'users', ['user_id'], ['id'])
    op.alter_column('discord_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('discord_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_chatbot_id_fkey', 'conversations', 'plubots', ['chatbot_id'], ['id'])
    op.alter_column('conversations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'conversation_states', type_='foreignkey')
    op.create_foreign_key('conversation_states_current_node_id_fkey', 'conversation_states', 'flows', ['current_node_id'], ['id'])
    op.alter_column('conversation_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conversation_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
