"""Renombrar plucoins a plu_coins

Revision ID: 9f0ced2eab9a
Revises: 
Create Date: 2025-04-22 19:21:19.971042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0ced2eab9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plu_coins', sa.Integer(), nullable=True))
        batch_op.drop_column('plucoins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plucoins', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('plu_coins')

    # ### end Alembic commands ###
