"""Add conversation_state table

Revision ID: a69b6a1294e0
Revises: 71a2253ef098
Create Date: 2025-06-23 05:35:50.116728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69b6a1294e0'
down_revision = '71a2253ef098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plubot_id', sa.Integer(), nullable=False),
    sa.Column('contact_identifier', sa.String(length=100), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['plubot_id'], ['plubots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_plubot_contact', 'conversation_states', ['plubot_id', 'contact_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_plubot_contact', table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
