"""increase_length_flow_edge_ids_handles

Revision ID: e3533f093a7a
Revises: 72c9fe56150a
Create Date: 2025-06-03 03:29:34.745300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3533f093a7a'
down_revision = '72c9fe56150a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_edges', 'frontend_id',
                   existing_type=sa.String(length=100),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    op.alter_column('flow_edges', 'source_handle',
                   existing_type=sa.String(length=50),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    op.alter_column('flow_edges', 'target_handle',
                   existing_type=sa.String(length=50),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_edges', 'target_handle',
                   existing_type=sa.String(length=255),
                   type_=sa.String(length=50),
                   existing_nullable=True)
    op.alter_column('flow_edges', 'source_handle',
                   existing_type=sa.String(length=255),
                   type_=sa.String(length=50),
                   existing_nullable=True)
    op.alter_column('flow_edges', 'frontend_id',
                   existing_type=sa.String(length=255),
                   type_=sa.String(length=100),
                   existing_nullable=True)
    # ### end Alembic commands ###
